### ISSUE TITLE
Receiving HTTP 500 errors from backend

### ISSUE THREAD

**Issue by sebastiankutschbach** [Flutter-Challenge/tinder_cat_dog_app#1]
Are there any known issues regarding this or am I just doing something wrong?

**Comment by dtengeri** [comment]
I checked the server logs, it fails when parsing the JWT token. So I think you send it in the wrong format.

**Comment by dtengeri** [comment]
Hold on it seems I found something.

**Comment by dtengeri** [comment]
Sorry, it was my fault, it should respond correctly now. I made changes in the server configuration before the challenge has been published, which went wrong. Thanks for raising this. 🙌 

You have to get another JWT token before posting your vote.

**Comment by sebastiankutschbach** [comment]
Works now. Thank you!
